opsui/lightCard: truncate overflowing preset titles
vanti-dev/sc-bos pull request #221
Opened 2024-02-24 15:45 UTC by richard-oven-vanti

This PR contains a fix for an issue, where long preset button text was overflowing to each side of the button.
This has been fixed with truncating the overflowing text while maintaining the texts centered position.

![Truncate long example preset title](https://github.com/vanti-dev/sc-bos/assets/131772660/2a1ac68a-5361-4ffa-b722-abcbed2c4189)

Jira: SC-464

2024-02-26 08:52 UTC, mattnathan requested changes

2024-02-26 08:52 UTC, mattnathan commented on ui/conductor/src/traits/lighting/LightCard.vue
> +}
This is _waaayyy_ more complicated than it needs to be

```html
<v-btn block ...>
  <span class="text-truncate">{{ preset.title ? preset.title : preset.name }}</span>
</v-btn>
```

Should be enough right?

2024-02-26 13:29 UTC, mattnathan requested changes

2024-02-26 13:29 UTC, mattnathan commented on ui/conductor/src/traits/lighting/LightCard.vue
This works for me:
```
<v-btn class="... preset" ...>
  <span class="text-truncate">{{ ... }}</span>
</v-btn>

<style scoped>
.preset ::v-deep(.v-btn__content) {
  max-width: 100%;
}
</style>
```

If you're going to change it to a list then you shouldn't need the enclosing div. But that's a bigger change than is needed to fix this

2024-02-26 13:56 UTC, richard-oven-vanti commented on ui/conductor/src/traits/lighting/LightCard.vue
I've kept it as a list and removed the div.

2024-02-27 09:51 UTC, mattnathan approved these changes

2024-02-27 10:27 UTC, merged