ui: Highlight selected light preset
vanti-dev/sc-bos pull request #238
Opened 2024-05-22 15:05 UTC by deanredfern26

Highlights the currently selected lighting preset with the primary colour

2024-05-22 15:06 UTC, deanredfern26 commented
https://vanti.youtrack.cloud/issue/OCW-19/remember-selected-lighting-preset-for-group-highlight-on-UI

2024-05-23 08:06 UTC, mattnathan requested changes
One small change, the rest looks good to me

2024-05-23 08:06 UTC, mattnathan commented on ui/conductor/src/traits/light/LightCard.vue
> +function getColour(title, currentPresetTitle) {
We use american english spelling for code words: Colour -> Color

2024-05-23 09:54 UTC, mattnathan approved these changes

2024-05-23 10:37 UTC, merged