SC-580: boot config load
vanti-dev/sc-bos pull request #262
Opened 2024-08-29 15:41 UTC by hexaglow

Implement the config loading flow at boot.

Supports loading local config from JSON file(s) (app.conf.json, same as current behaviour), detecting changes between the current local config and the previous local config (at last boot). It then applies all these changes to the active config, which is stored in the data directory.

The challenge is that the active config can be changed at any time by the user (e.g. via the UI) and these changes will not be reflected in the manually written / generated external config files. By using a content-aware diff of the local config, we can produce a list of narrow patches which won't squash any user changes (unless the user has changed the same thing as the local config).

A copy of the previous local config is stored in `<data_dir>/config/local.json` to be used for diffing on next boot. The active config (the config actually used by the system) is stored in `<data_dir>/config/active.json`.
Whenever patches are applied, they are saved in the config directory to allow diagnosis if changes are applied incorrectly.

Uses the `block` package to perform content-aware JSON diffs. By default, each driver/auto/zone is a single block. More specific Blocks can be defined by driver (or automation / zone) factories that implement the `sysconf.BlockSource` interface. Implementation for existing drivers is not included in this PR.

2024-08-30 15:07 UTC, mattnathan requested changes
I'm not sure I like the term `local config` - it doesn't immediately describe what it is for me. I understand that the config is local, but for me local is mostly useful as a partner with `remote` or `external`, and that's not how it's used here - especially as there are multiple local config files now.

Maybe something more along the `file config` path would be better, or `factory` or `default` might work, `native` or `base` also, though I know they also have connotations?

2024-09-02 12:05 UTC, hexaglow commented on pkg/app/appconf/boot.go
> +}
We need this to run on Windows - but it doesn't need to be atomic. So `maybe.WriteFile` fits the bill well.

2024-09-02 14:09 UTC, hexaglow commented on pkg/app/sysconf/config.go
> +type BlockSource interface {
I don't like that because it reads as a verb, which it isn't.
It's not a "think that blocks configs", it's a "thing that provides blocks"

2024-09-02 14:13 UTC, hexaglow commented on pkg/app/appconf/testdata/boot.txtar
They were present in Dean's original draft of the PR. I converted them from individual JSON files but the tests they were referenced from no longer exist.

They might still be useful because they represent 'realistic' config files. But for now I'll remove them.

2024-09-02 14:14 UTC, hexaglow commented
@mattnathan I might change 'local config' to 'external config' - as in "config that comes from outside Smart Core-managed storage". What do you think?

2024-09-04 09:51 UTC, hexaglow commented
@mattnathan OK, I've changed the term 'local' to 'external'. Ready for a review now.

2024-09-04 10:00 UTC, mattnathan requested changes

2024-09-04 11:11 UTC, mattnathan requested changes

2024-09-04 11:11 UTC, mattnathan commented on pkg/app/controller.go
> +	ref, err := store.SavePatches(patches)
I'm not sure SavePatches deserves to be a method on store anymore considering it's not used by the confmerge package at all.

2024-09-04 12:40 UTC, mattnathan approved these changes

2024-09-04 13:17 UTC, merged